### ISSUE TITLE
Lock instead of sleep?

### ISSUE THREAD

**Issue by TechnologyClassroom** [ErfanSn/ES-Timer#1]
Cool project!

I am interested in modifying ES-Timer to lock the machine instead of sending it to sleep as sleep breaks the WiFi connection and I work with remote servers frequently.  I could just use `tmux` or `screen` after I remote in, but locking the screen would be simple.  Locking instead of sleeping also has a security benefit of ensuring someone else cannot press the power button to access the machine while away on a break.

With `DigiKeyboard.h`, the method to send the CTRL+ALT+l keystroke would be like this:

    DigiKeyboard.sendKeyStroke(KEY_L, MOD_ALT_LEFT | MOD_CONTROL_LEFT);

Can you help me understand which line of code is doing the sleep key?  Is it this line in `ESTimer.h` within [ESTimer.zip](https://github.com/ErfanSn/ES-Timer/blob/master/lib/ESTimer.zip)?

    #define SLEEP           0x82

If that is correct, do you know how to send multiple keys to build a keystroke in this way without using `DigiKeyboard.h`?

**Comment by ErfanSn** [comment]
Thank you for your comment on the project.
After the project was posted on [hackaday](https://hackaday.com/2021/10/31/cherry-pomodoro-timer-forces-you-to-follow/), in the comments that were written there about the timer, I realized that falling sleep mode is a problem for some people, so I am looking for a way to solve this problem. if I can not implement the method I have in mind, I will apply the method you suggested, ie locking the system, but in order for the timer to understand that you want to start your next task, a button must be added to the timer.

If you look closely at the ES Timer codes, I actually used the integration and modification of `DigisparkOLED` and `DigisparkKeyboard`, to create timers due to lack of flash memory. `DigisparkKeyboard` itself uses the [V-USB](https://www.obdev.at/products/vusb/download.html) framework

To learn more about HID, I suggest you visit [this](https://usb.org/). Of course, the documentation on this reference site is a bit complicated, so you can get help from other sites that explain HID more easily.

**Comment by ErfanSn** [comment]
Good news
I will release the second version of ES Timer by tomorrow or the day after tomorrow, the lock screen has replaced sleep and there is no need to upgrade the timer hardware.
